version: '3.8'

services:
  dotnet-app:
    build:
      context: ./customer-success-platformServer
      dockerfile: Dockerfile2
    ports:
      - "4437:4437"  
    depends_on:
      - postgres
      - migration-service
    environment:
       Database: CustomerSuccessPlatformDB
       Username: postgres
       Password: 123456
        

  angular-app:
    build:
      context: ./CustomerSuccessPlatform
      dockerfile: Dockerfile1
    ports:
      - "4200:4200"  
    command: npm start -- --host 0.0.0.0
    depends_on:
      - dotnet-app
  migration-service:  # Service for running migrations
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ./customer-success-platformServer:/app  # Mount the application code
    depends_on:
      - postgres
    environment:
      Database: CustomerSuccessPlatformDB
      Username: postgres
      Password: 123456
    command: >
      bash -c "dotnet tool install --global dotnet-ef && 
               cd /app && 
               dotnet ef database update"
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: postgres
      POSTGRES_DB: CustomerSuccessPlatformDB
    volumes:
     - type: volume
       source: db-data
       target: /var/lib/postgresql/data
volumes:
  db-data:
    